AWSTemplateFormatVersion: '2010-09-09'
Description: 'AWS Glue ETL Job for processing Appraisal Notices CSV data from S3 to Aurora PostgreSQL'

Parameters:
  GlueServiceRoleArn:
    Type: String
    Description: 'ARN of the Glue service role with necessary permissions'
    Default: 'arn:aws:iam::006559585423:role/dcad-csv-to-database-etl-role'

  GlueConnectionName:
    Type: String
    Description: 'Name of the Glue connection for VPC access'
    Default: 'dcad-csv-to-database-etl-database-connection'

  ScriptLocation:
    Type: String
    Description: 'S3 location of the Glue ETL script'
    Default: 's3://aws-glue-assets-006559585423-us-west-2/scripts/appraisal_notices_etl.py'

Resources:
  AppraisalNoticesETLJob:
    Type: AWS::Glue::Job
    Properties:
      Name: 'appraisal-notices-etl'
      Description: 'ETL job to process appraisal notices data from S3 CSV files to Aurora PostgreSQL'
      Role: !Ref GlueServiceRoleArn
      Command:
        Name: 'glueetl'
        ScriptLocation: !Ref ScriptLocation
        PythonVersion: '3'
      DefaultArguments:
        '--job-language': 'python'
        '--job-bookmark-option': 'job-bookmark-disable'
        '--CONNECTION_NAME': !Ref GlueConnectionName
        '--SOURCE_BUCKET': 'map-appraiser-data-raw-appraisal'
        '--DB_NAME': 'map_appraiser'
      Connections:
        Connections:
          - !Ref GlueConnectionName  # CRITICAL: VPC connection for database access
      ExecutionProperty:
        MaxConcurrentRuns: 1
      MaxRetries: 0
      Timeout: 2880  # 48 hours max timeout
      MaxCapacity: 2.0
      GlueVersion: '4.0'
      Tags:
        Project: 'map-appraiser'
        Environment: 'development'
        DataSource: 'appraisal-notices'
        Purpose: 'etl-processing'

Outputs:
  JobName:
    Description: 'Name of the created Glue ETL job'
    Value: !Ref AppraisalNoticesETLJob
    Export:
      Name: !Sub '${AWS::StackName}-JobName'

  JobArn:
    Description: 'ARN of the created Glue ETL job'
    Value: !Sub 'arn:aws:glue:${AWS::Region}:${AWS::AccountId}:job/${AppraisalNoticesETLJob}'
    Export:
      Name: !Sub '${AWS::StackName}-JobArn'