AWSTemplateFormatVersion: '2010-09-09'
Description: 'AWS Glue ETL Job to load DCAD CSV data into Aurora PostgreSQL database'

Parameters:
  JobName:
    Type: String
    Default: dcad-csv-to-database-etl
    Description: Name of the Glue ETL job
    
  SourceBucket:
    Type: String
    Default: map-appraiser-data-raw-appraisal
    Description: S3 bucket containing the CSV source data
    
  DatabaseHost:
    Type: String
    Default: map-appraiser-aurora-db-cluster.cluster-cjcydnj4gvc0.us-west-2.rds.amazonaws.com
    Description: Aurora PostgreSQL database host
    
  DatabasePort:
    Type: String
    Default: '5432'
    Description: Database port
    
  DatabaseName:
    Type: String
    Default: map_appraiser
    Description: Database name
    
  DatabaseUser:
    Type: String
    Default: postgres
    Description: Database user
    
  DatabaseSecretName:
    Type: String
    Default: aurora-postgres-password
    Description: AWS Secrets Manager secret containing database password
    
  GlueVersion:
    Type: String
    Default: '4.0'
    Description: Glue version to use
    AllowedValues: ['3.0', '4.0']
    
  MaxCapacity:
    Type: Number
    Default: 2
    Description: Maximum capacity for the Glue job (DPUs for glueetl)
    MinValue: 2
    MaxValue: 100

Resources:
  # IAM Role for Glue Job
  GlueJobRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${JobName}-role'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: glue.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSGlueServiceRole
      Policies:
        - PolicyName: S3Access
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:ListBucket
                Resource:
                  - !Sub 'arn:aws:s3:::${SourceBucket}'
                  - !Sub 'arn:aws:s3:::${SourceBucket}/*'
        - PolicyName: SecretsManagerAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                Resource: !Sub 'arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:${DatabaseSecretName}*'
        - PolicyName: VPCAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - ec2:CreateNetworkInterface
                  - ec2:DeleteNetworkInterface
                  - ec2:DescribeNetworkInterfaces
                  - ec2:DescribeVpcs
                  - ec2:DescribeSubnets
                  - ec2:DescribeSecurityGroups
                  - ec2:AttachNetworkInterface
                  - ec2:DetachNetworkInterface
                Resource: '*'
        - PolicyName: CloudWatchLogs
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: !Sub 'arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws-glue/*'

  # Security Group for Glue Job (if VPC access needed)
  GlueSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub '${JobName}-sg'
      GroupDescription: Security group for Glue ETL job
      VpcId: vpc-0b6198ac5cdb4c1ab
      SecurityGroupEgress:
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0
          Description: HTTPS outbound for AWS services
        - IpProtocol: tcp
          FromPort: 5432
          ToPort: 5432
          DestinationSecurityGroupId: sg-0cb3f978b24e43fd8
          Description: PostgreSQL database access to Aurora
      Tags:
        - Key: Name
          Value: !Sub '${JobName}-security-group'

  # Self-referencing ingress rule for Glue communication
  GlueSecurityGroupIngressRule:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId: !Ref GlueSecurityGroup
      IpProtocol: -1
      SourceSecurityGroupId: !Ref GlueSecurityGroup
      Description: Self-referencing rule for Glue communication

  # Self-referencing egress rule for Glue communication
  GlueSecurityGroupEgressRule:
    Type: AWS::EC2::SecurityGroupEgress
    Properties:
      GroupId: !Ref GlueSecurityGroup
      IpProtocol: -1
      DestinationSecurityGroupId: !Ref GlueSecurityGroup
      Description: Self-referencing rule for Glue communication

  # VPC Endpoint for S3 access in Aurora VPC
  S3VPCEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      VpcId: vpc-0b6198ac5cdb4c1ab
      ServiceName: !Sub 'com.amazonaws.${AWS::Region}.s3'
      VpcEndpointType: Gateway
      RouteTableIds:
        - rtb-0880e3f59b8f6ffcb

  # Add ingress rule to Aurora security group for Glue access
  AuroraIngressRule:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId: sg-0cb3f978b24e43fd8
      IpProtocol: tcp
      FromPort: 5432
      ToPort: 5432
      SourceSecurityGroupId: !Ref GlueSecurityGroup
      Description: Allow Glue ETL job access to Aurora PostgreSQL

  # Glue Connection for database access
  GlueConnection:
    Type: AWS::Glue::Connection
    Properties:
      CatalogId: !Ref AWS::AccountId
      ConnectionInput:
        Name: !Sub '${JobName}-database-connection'
        Description: 'Connection to Aurora PostgreSQL database'
        ConnectionType: JDBC
        ConnectionProperties:
          JDBC_CONNECTION_URL: !Sub 'jdbc:postgresql://${DatabaseHost}:${DatabasePort}/${DatabaseName}'
          USERNAME: !Ref DatabaseUser
          PASSWORD: !Sub '{{resolve:secretsmanager:${DatabaseSecretName}:SecretString}}'
        PhysicalConnectionRequirements:
          SubnetId: subnet-032ce24e76c7a63e5
          SecurityGroupIdList:
            - !Ref GlueSecurityGroup
          AvailabilityZone: us-west-2b

  # Glue ETL Job
  CSVToDatabaseJob:
    Type: AWS::Glue::Job
    Properties:
      Name: !Ref JobName
      Description: 'ETL job to load DCAD CSV data into Aurora PostgreSQL database'
      Role: !GetAtt GlueJobRole.Arn
      GlueVersion: !Ref GlueVersion
      MaxCapacity: !Ref MaxCapacity
      Timeout: 2880  # 48 hours
      MaxRetries: 1
      Command:
        Name: glueetl
        PythonVersion: '3'
        ScriptLocation: !Sub 's3://aws-glue-assets-${AWS::AccountId}-${AWS::Region}/scripts/csv_to_database_etl_v2.py'
      DefaultArguments:
        '--job-language': 'python'
        '--job-bookmark-option': 'job-bookmark-disable'
        '--enable-metrics': 'true'
        '--enable-continuous-cloudwatch-log': 'true'
        '--SOURCE_BUCKET': !Ref SourceBucket
        '--CONNECTION_NAME': !Ref GlueConnection
        '--DB_NAME': !Ref DatabaseName
      Connections:
        Connections:
          - !Ref GlueConnection
      Tags:
        Environment: development
        Project: map-appraiser
        Component: etl

Outputs:
  JobName:
    Description: 'Name of the created Glue job'
    Value: !Ref CSVToDatabaseJob
    Export:
      Name: !Sub '${AWS::StackName}-JobName'
      
  JobArn:
    Description: 'ARN of the created Glue job'
    Value: !Sub 'arn:aws:glue:${AWS::Region}:${AWS::AccountId}:job/${JobName}'
    Export:
      Name: !Sub '${AWS::StackName}-JobArn'
      
  GlueRoleArn:
    Description: 'ARN of the Glue service role'
    Value: !GetAtt GlueJobRole.Arn
    Export:
      Name: !Sub '${AWS::StackName}-GlueRoleArn'
      
  DatabaseConnectionName:
    Description: 'Name of the Glue database connection'
    Value: !Ref GlueConnection
    Export:
      Name: !Sub '${AWS::StackName}-DatabaseConnection'

  ScriptUploadCommand:
    Description: 'AWS CLI command to upload the ETL script'
    Value: !Sub 'aws s3 cp csv_to_database_etl.py s3://aws-glue-assets-${AWS::AccountId}-${AWS::Region}/scripts/'
      
  JobRunCommand:
    Description: 'AWS CLI command to run the ETL job'
    Value: !Sub 'aws glue start-job-run --job-name ${JobName}'
    
  JobRunWithYearCommand:
    Description: 'AWS CLI command to run the ETL job for specific year'
    Value: !Sub 'aws glue start-job-run --job-name ${JobName} --arguments="--TARGET_YEAR=2025"'