AWSTemplateFormatVersion: '2010-09-09'
Description: 'AWS Glue ETL Job for converting CSV files to individual JSON files'

Parameters:
  GlueJobName:
    Type: String
    Default: map-appraiser-csv-to-json-etl
    Description: Name of the Glue job
  
  GlueScriptLocation:
    Type: String
    Description: S3 location of the Glue script
    Default: s3://map-appraiser-glue-scripts/csv_to_json_etl.py
  
  GlueServiceRoleName:
    Type: String
    Default: MapAppraiserGlueServiceRole
    Description: Name for the Glue service role

Resources:
  # S3 Bucket for Glue scripts
  GlueScriptsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: map-appraiser-glue-scripts
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  # IAM Role for Glue Job
  GlueServiceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Ref GlueServiceRoleName
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - glue.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSGlueServiceRole
      Policies:
        - PolicyName: S3AccessPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:ListBucket
                Resource:
                  - arn:aws:s3:::map-appraiser-data-raw-appraisal
                  - arn:aws:s3:::map-appraiser-data-raw-appraisal/*
              - Effect: Allow
                Action:
                  - s3:PutObject
                  - s3:GetObject
                  - s3:ListBucket
                Resource:
                  - arn:aws:s3:::map-appraiser-data-knowledge-base
                  - arn:aws:s3:::map-appraiser-data-knowledge-base/*
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:ListBucket
                Resource:
                  - !Sub 'arn:aws:s3:::${GlueScriptsBucket}'
                  - !Sub 'arn:aws:s3:::${GlueScriptsBucket}/*'
        - PolicyName: CloudWatchLogsPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: '*'

  # Glue Job
  CsvToJsonGlueJob:
    Type: AWS::Glue::Job
    Properties:
      Name: !Ref GlueJobName
      Role: !GetAtt GlueServiceRole.Arn
      Command:
        Name: glueetl
        ScriptLocation: !Ref GlueScriptLocation
        PythonVersion: '3'
      DefaultArguments:
        '--enable-metrics': 'true'
        '--enable-continuous-cloudwatch-log': 'true'
        '--enable-spark-ui': 'true'
        '--spark-event-logs-path': !Sub 's3://${GlueScriptsBucket}/spark-logs/'
        '--job-bookmark-option': 'job-bookmark-enable'
        '--job-language': 'python'
        '--TempDir': !Sub 's3://${GlueScriptsBucket}/temp/'
      ExecutionProperty:
        MaxConcurrentRuns: 1
      GlueVersion: '4.0'
      MaxRetries: 0
      NumberOfWorkers: 10
      WorkerType: G.1X
      Timeout: 2880  # 48 hours timeout for large datasets
      Description: 'ETL job to convert CSV files to individual JSON files for knowledge base'

Outputs:
  GlueJobName:
    Description: Name of the created Glue job
    Value: !Ref CsvToJsonGlueJob
  
  GlueServiceRoleArn:
    Description: ARN of the Glue service role
    Value: !GetAtt GlueServiceRole.Arn
  
  GlueScriptsBucketName:
    Description: Name of the S3 bucket for Glue scripts
    Value: !Ref GlueScriptsBucket
  
  GlueScriptUploadCommand:
    Description: Command to upload the Glue script to S3
    Value: !Sub |
      aws s3 cp glue-data-preparation/csv_to_json_etl.py s3://${GlueScriptsBucket}/csv_to_json_etl.py