AWSTemplateFormatVersion: '2010-09-09'
Description: 'AWS Glue ETL Job for converting Shapefiles to individual GeoJSON files'

Parameters:
  GlueJobName:
    Type: String
    Default: map-appraiser-shapefile-to-geojson-etl
    Description: Name of the Glue job
  
  GlueScriptLocation:
    Type: String
    Description: S3 location of the Glue script
    Default: s3://map-appraiser-glue-scripts/shapefile_to_geojson_etl.py
  
  GlueServiceRoleName:
    Type: String
    Default: MapAppraiserShapefileGlueServiceRole
    Description: Name for the Glue service role

Resources:
  # IAM Role for Glue Job (separate from CSV job role)
  ShapefileGlueServiceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Ref GlueServiceRoleName
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - glue.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSGlueServiceRole
      Policies:
        - PolicyName: S3AccessPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:ListBucket
                Resource:
                  - arn:aws:s3:::map-appraiser-data-raw-gis
                  - arn:aws:s3:::map-appraiser-data-raw-gis/*
              - Effect: Allow
                Action:
                  - s3:PutObject
                  - s3:GetObject
                  - s3:ListBucket
                Resource:
                  - arn:aws:s3:::map-appraiser-data-knowledge-base
                  - arn:aws:s3:::map-appraiser-data-knowledge-base/*
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:ListBucket
                Resource:
                  - arn:aws:s3:::map-appraiser-glue-scripts
                  - arn:aws:s3:::map-appraiser-glue-scripts/*
        - PolicyName: CloudWatchLogsPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: '*'

  # Glue Job
  ShapefileToGeoJsonGlueJob:
    Type: AWS::Glue::Job
    Properties:
      Name: !Ref GlueJobName
      Role: !GetAtt ShapefileGlueServiceRole.Arn
      Command:
        Name: glueetl
        ScriptLocation: !Ref GlueScriptLocation
        PythonVersion: '3'
      DefaultArguments:
        '--enable-metrics': 'true'
        '--enable-continuous-cloudwatch-log': 'true'
        '--enable-spark-ui': 'true'
        '--spark-event-logs-path': 's3://map-appraiser-glue-scripts/spark-logs/'
        '--job-bookmark-option': 'job-bookmark-enable'
        '--job-language': 'python'
        '--TempDir': 's3://map-appraiser-glue-scripts/temp/'
        # Additional Python libraries needed for geospatial processing
        '--additional-python-modules': 'geopandas==0.14.1,shapely==2.0.2,pyproj==3.6.1,fiona==1.9.5'
        # Use G.2X workers for more memory (geospatial operations can be memory intensive)
      ExecutionProperty:
        MaxConcurrentRuns: 1
      GlueVersion: '4.0'
      MaxRetries: 0
      NumberOfWorkers: 5
      WorkerType: G.2X
      Timeout: 2880  # 48 hours timeout for large datasets
      Description: 'ETL job to convert Shapefiles to individual GeoJSON files for knowledge base'

Outputs:
  GlueJobName:
    Description: Name of the created Glue job
    Value: !Ref ShapefileToGeoJsonGlueJob
  
  GlueServiceRoleArn:
    Description: ARN of the Glue service role
    Value: !GetAtt ShapefileGlueServiceRole.Arn
  
  GlueScriptUploadCommand:
    Description: Command to upload the Glue script to S3
    Value: !Sub |
      aws s3 cp shapefile_to_geojson_etl.py s3://map-appraiser-glue-scripts/shapefile_to_geojson_etl.py